config/routes.rb
Rails.application.routes.draw do
  resources :bombas
  resources :clientes do
    member do
      get 'bombas', to: 'clientes#bombas'
    end
  end  
  resources :empleados
  resources :paises
  resources :ciudades
  resources :ubicaciones
  resources :cargos
  # Defines the root path route ("/")
  root "personas#index"
  resources :personas
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/cliente.rb
class Cliente < ApplicationRecord
    has_and_belongs_to_many :bombas
    validates :nombre, :razon_social, :ruc, presence: true
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: %i[ show edit update destroy ]

  # GET /clientes or /clientes.json
  def index
    @clientes = Cliente.all
  end

  # GET /clientes/1 or /clientes/1.json
  def show
    @cliente = Cliente.find(params[:id])
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
    @bombas = Bomba.all # Fetch all bombas for the dropdown
  end

  # GET /clientes/1/edit
  def edit
    @cliente = Cliente.find(params[:id])
    @bombas = Bomba.all # Fetch all bombas for the dropdown
  end

  # POST /clientes or /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: "EL cliente ha sido creado" }
        format.json { render :show, status: :created, location: @cliente }
      else
        @bombas = Bomba.all # Fetch all bombas again for the dropdown in case of errors
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1 or /clientes/1.json
  def update
    respond_to do |format|
    @cliente = Cliente.find(params[:id])
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: "El cliente ha sido modificado con exito" }
        format.json { render :show, status: :ok, location: @cliente }
      else
        @bombas = Bomba.all # Fetch all bombas again for the dropdown in case of errors
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1 or /clientes/1.json
  def destroy
    @cliente.destroy

    respond_to do |format|
      format.html { redirect_to clientes_path, status: :see_other, notice: "El cliente ha sido eliminado exitosamente" }
      format.json { head :no_content }
    end
  end

  def bombas
    @cliente = Cliente.find(params[:id])
    bombas = @cliente.bombas.select(:descripcion, :coordenadas)
    render json: bombas
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cliente_params
      params.require(:cliente).permit(:nombre, :razon_social, :ruc, bomba_ids: [])
    end    

  end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/_form.html.erb
<%= form_with(model: cliente) do |form| %>
  <% if cliente.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(cliente.errors.count, "error") %> no se puede guardar:</h2>

      <ul>
        <% cliente.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <% if @cliente.errors.include?(:bomba_id) %>
  <div class="alert alert-danger" role="alert">
    ¡Debes seleccionar un bomba!
  </div>
  <% end %>

  <div class="form-group mb-3">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, class: 'form-control' %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :razon_social %>
    <%= form.text_field :razon_social, class: 'form-control' %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :ruc %>
    <%= form.text_field :ruc, class: 'form-control' %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :bombas %> (Selecciona una o más bombas)<br>
    <div class="form-check">
      <% Bomba.all.each do |bomba| %>
        <div class="form-check">
          <%= check_box_tag 'cliente[bomba_ids][]', bomba.id, @cliente.bomba_ids.include?(bomba.id), class: "form-check-input" %>
          <%= label_tag "bomba_#{bomba.id}", bomba.descripcion, class: "form-check-label" %>
        </div>
      <% end %>      
    </div>
  </div>

  <div class="d-flex justify-content-end">
    <%= form.submit 'Guardar', class: 'btn btn-primary me-2' %>
    <%= link_to 'Cancelar', clientes_path, class: 'btn btn-secondary' %>
  </div>
<% end %>

app/views/clientes/edit.html.erb
<h1>Editar Cliente</h1>

<%= render 'form', cliente: @cliente %>

app/views/clientes/index.html.erb
<div class="jumbotron bg-primary text-white">
  <h1 class="display-4">Clientes</h1>
</div>

  <% if notice %>
    <p class="alert alert-info"><%= notice %></p>
  <% end %>

  <table class="table table-striped" style="margin: 0; padding: 0;">
    <thead>
      <tr>
        <th scope="col">Id</th>
        <th scope="col">Nombre</th>
        <th scope="col">Razon Social</th>
        <th scope="col">RUC</th>
        <th scope="col">Bombas</th>
        <th colspan="3" class="text-center">Acciones</th>
      </tr>
    </thead>

    <tbody>
      <% @clientes.each do |cliente| %>
        <tr>
          <th scope="row"><%= cliente.id %></th>
          <td><%= cliente.nombre %></td>
          <td><%= cliente.razon_social %></td>
          <td><%= cliente.ruc %></td>
          <td>
            <ul>
              <% cliente.bombas.each do |bomba| %>
                <li><%= bomba.descripcion %></li>
              <% end %>
            </ul>
          </td>
          <td class="col-md-2 text-center">
            <%= link_to 'Mostrar', cliente, class: "btn btn-warning" %>
          </td>
          <td class="col-md-2 text-center">
            <%= link_to 'Editar', edit_cliente_path(cliente), class: "btn btn-primary" %>
          </td>
          <td class="col-md-2 text-center">
            <%= link_to 'Borrar', cliente, method: :delete, data: { confirm: 'Estas seguro?' }, class: "btn btn-danger" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to "Nuevo cliente", new_cliente_path, class: "btn btn-success opacity-75" %>

  <!-- Selector de cliente -->
<div class="form-group mb-3">
  <label for="cliente-select">Selecciona un cliente para mostrar las bombas en el mapa:</label>
  <select id="cliente-select" class="form-control" onchange="loadClientBombas(this.value)">
    <option value="">Seleccionar cliente</option>
    <% @clientes.each do |cliente| %>
      <option value="<%= cliente.id %>"><%= cliente.nombre %></option>
    <% end %>
  </select>
</div>

<!-- Contenedor del mapa -->
<!-- Div contenedor del mapa -->
<div id="map" style="height: 500px; width: 100%;"></div>

<script>
  let map;
  let markers = []; // Inicializamos el array de marcadores
  
  // Inicializar el mapa
  function initMap() {
    map = new google.maps.Map(document.getElementById('map'), {
      center: { lat: -24, lng: -56 }, // Coordenadas iniciales
      zoom: 5,
    });
  }
  
  // Cargar bombas de un cliente
  function loadClientBombas(clienteId) {
    console.log("Cargando bombas para cliente:", clienteId);
    
    if (!clienteId) return;

    fetch(`/clientes/${clienteId}/bombas.json`)
      .then(response => response.json())
      .then(bombas => {
        console.log("Bombas recibidas:", bombas);
        clearMarkers();

        //Create an empty bounds object
        const bounds = new google.maps.LatLngBounds();

        bombas.forEach(bomba => {
          const coords = bomba.coordenadas.split(',');
          const lat = parseFloat(coords[0]);
          const lng = parseFloat(coords[1]);

          const marker = new google.maps.Marker({
            position: { lat, lng },
            map,
            title: bomba.descripcion
          });
          markers.push(marker); // Añadimos cada marcador al array
          bounds.extend({ lat, lng });
        });
        // Fit the map to the bounds containing all markers
        map.fitBounds(bounds);
      });
  }
 
  // Eliminar los marcadores del mapa
  function clearMarkers() {
    for (let i = 0; i < markers.length; i++) {
      markers[i].setMap(null); // Eliminar cada marcador del mapa
    }
    markers = []; // Vaciamos el array de marcadores
  }
</script>

<!-- Carga de Google Maps API con callback para inicializar el mapa -->
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBpGDeQen8q4HDG9bKfTywSMU8B_L7rm5A&callback=initMap"></script>


  <div class="mt-3 p-3">
    <div class="row">
      <div class="col-12">
        </div>
    </div>
  </div>
</div>

app/views/clientes/new.html.erb
<h1>Nuevo Cliente</h1>

<%= render 'form', cliente: @cliente %>

app/views/clientes/show.html.erb
<div class="container mt-4">
  <!-- Notificación -->
  <% if notice %>
    <div class="alert alert-info alert-dismissible fade show" role="alert" id="notice">
      <%= notice %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>

  <!-- Detalles del Cliente -->
  <div class="card shadow-sm">
    <div class="card-body">
      <h2 class="card-title mb-4">Detalles del Cliente</h2>

      <!-- Cliente -->
      <p class="mb-3">
        <strong>Cliente:</strong>
        <span class="text-muted"><%= @cliente.nombre %></span>
      </p>

      <!-- Razon Social -->
      <p class="mb-3">
        <strong>Razon Social:</strong>
        <span class="text-muted"><%= @cliente.razon_social %></span>
      </p>

      <!-- RUC -->
      <p class="mb-3">
        <strong>RUC:</strong>
        <span class="text-muted"><%= @cliente.ruc %></span>
      </p>

      <!-- Bomba -->
      <p class="mb-4">
      <strong>Bombas:</strong>
        <ul>
          <% @cliente.bombas.each do |bomba| %>
          <li><%= bomba.descripcion %></li>
        <% end %>
        </ul>
      </p>


      <!-- Botones de acción -->
      <div class="d-flex justify-content-between">
        <%= link_to 'Editar', edit_cliente_path(@cliente), class: "btn btn-primary me-2" %>
        <%= link_to 'Volver', clientes_path, class: "btn btn-secondary" %>
      </div>
    </div>
  </div>
</div>