config/routes.rb
Rails.application.routes.draw do
  resources :bombas
  resources :clientes do
    member do
      get 'bombas', to: 'clientes#bombas'
    end
  end  
  resources :empleados
  resources :paises
  resources :ciudades
  resources :ubicaciones
  resources :cargos
  # Defines the root path route ("/")
  root "personas#index"
  resources :personas
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/cargo.rb
class Cargo < ApplicationRecord
    has_many :personas
end

app/controllers/cargos_controller.rb
class CargosController < ApplicationController
  before_action :set_cargo, only: %i[ show edit update destroy ]

  # GET /cargos or /cargos.json
  def index
    @cargos = Cargo.all
  end

  # GET /cargos/1 or /cargos/1.json
  def show
  end

  # GET /cargos/new
  def new
    @cargo = Cargo.new
  end

  # GET /cargos/1/edit
  def edit
  end

  # POST /cargos or /cargos.json
  def create
    @cargo = Cargo.new(cargo_params)

    respond_to do |format|
      if @cargo.save
        format.html { redirect_to @cargo, notice: "Cargo was successfully created." }
        format.json { render :show, status: :created, location: @cargo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cargo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cargos/1 or /cargos/1.json
  def update
    respond_to do |format|
      if @cargo.update(cargo_params)
        format.html { redirect_to @cargo, notice: "Cargo was successfully updated." }
        format.json { render :show, status: :ok, location: @cargo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cargo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cargos/1 or /cargos/1.json
  def destroy
    @cargo.destroy

    respond_to do |format|
      format.html { redirect_to cargos_path, status: :see_other, notice: "Cargo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cargo
      @cargo = Cargo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cargo_params
      params.require(:cargo).permit(:descripcion, :sueldo)
    end
end

app/helpers/cargos_helper.rb
module CargosHelper
end

app/views/cargos/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">

      <%= simple_form_for(@cargo) do |f| %>
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

        <div class="card">
          <div class="card-body">
            <%= f.input :descripcion, label: 'Descripción', input_html: { class: 'form-control' } %>
            <%= f.input :sueldo, label: 'Sueldo', input_html: { class: 'form-control' } %>
          </div>
        </div>

        <div class="card-footer text-center">
          <%= f.button :submit, value: 'Guardar', class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/cargos/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h2 class="text-center mb-4">Editar Cargo</h2>

      <div class="card">
        <div class="card-body">
          <%= render 'form', cargo: @cargo %>
        </div>
      </div>

      <div class="card-footer text-center">
        <%= link_to 'Mostrar', @cargo, class: 'btn btn-secondary' %> |
        <%= link_to 'Volver', cargos_path, class: 'btn btn-secondary' %>
      </div>
    </div>
  </div>
</div>

app/views/cargos/index.html.erb
<div class="jumbotron bg-primary text-white">
  <h1 class="display-4">  Cargos </h1>
</div>

  <% if notice %>
    <p class="alert alert-info"><%= notice %></p>
  <% end %>


      <table class="table table-bordered">
        <thead>
          <tr>
            <th>ID</th>
            <th>Descripción</th>
            <th>Sueldo</th>
            <th colspan="3">Acciones</th>
          </tr>
        </thead>

        <tbody>
          <% @cargos.each do |cargo| %>
            <tr>
              <td><%= cargo.id %></td>
              <td><%= cargo.descripcion %></td>
              <td><%= number_to_currency cargo.sueldo %></td>
              <td><%= link_to 'Mostrar', cargo, class: 'btn btn-sm btn-primary' %></td>
              <td><%= link_to 'Editar', edit_cargo_path(cargo), class: 'btn btn-sm btn-warning' %></td>
              <td><%= link_to 'Borrar', cargo, method: :delete, data: { confirm: '¿Estás seguro?' }, class: 'btn btn-sm btn-danger' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <div class="text-center mt-3">
        <%= link_to 'Nuevo Cargo', new_cargo_path, class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
</div>

app/views/cargos/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card">
        <div class="card-header">
          <h1>Nuevo Cargo</h1>
        </div>
        <div class="card-body">
          <%= render 'form', cargo: @cargo %>
        </div>
      </div>
      <div class="text-center mt-3">
        <%= link_to 'Volver', cargos_path, class: 'btn btn-secondary' %>
      </div>
    </div>
  </div>
</div>

app/views/cargos/show.html.erb
<div class="card">
  <div class="card-body">
    <p class="card-text">
      <%= notice %>
    </p>

    <dl class="row">
      <dt class="col-sm-3">ID:</dt>
      <dd class="col-sm-9"><%= @cargo.id %></dd>
      
      <dt class="col-sm-3">Descripción:</dt>
      <dd class="col-sm-9"><%= @cargo.descripcion %></dd>

      <dt class="col-sm-3">Sueldo:</dt>
      <dd class="col-sm-9"><%= number_to_currency @cargo.sueldo %></dd>
    </dl>

    <div class="d-flex justify-content-end">
      <%= link_to 'Editar', edit_cargo_path(@cargo), class: 'btn btn-primary' %>
      <%= link_to 'Volver', cargos_path, class: 'btn btn-secondary ml-2' %>
    </div>
  </div>
</div>