config/routes.rb
Rails.application.routes.draw do
  resources :bombas
  resources :clientes do
    member do
      get 'bombas', to: 'clientes#bombas'
    end
  end  
  resources :empleados
  resources :paises
  resources :ciudades
  resources :ubicaciones
  resources :cargos
  # Defines the root path route ("/")
  root "personas#index"
  resources :personas
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/persona.rb
class Persona < ApplicationRecord
    belongs_to :cargo
    validates :nombre, :edad, :cargo_id, presence: true
  end
  

app/controllers/personas_controller.rb
class PersonasController < ApplicationController
  before_action :set_persona, only: %i[ show edit update destroy ]

  # GET /personas or /personas.json
  def index
    @personas = Persona.all
  end

  # GET /personas/1 or /personas/1.json
  def show
    @persona = Persona.find(params[:id])
  end

  # GET /personas/new
  def new
    @persona = Persona.new
    @cargos = Cargo.all # Fetch all cargos for the dropdown
  end

  # GET /personas/1/edit
  def edit
    @persona = Persona.find(params[:id])
    @cargos = Cargo.all # Fetch all cargos for the dropdown
  end

  # POST /personas or /personas.json
  def create
    @persona = Persona.new(persona_params)

    respond_to do |format|
      if @persona.save
        format.html { redirect_to @persona, notice: "La persona ha sido creada" }
        format.json { render :show, status: :created, location: @persona }
      else
        @cargos = Cargo.all # Fetch all cargos again for the dropdown in case of errors
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personas/1 or /personas/1.json
  def update
    respond_to do |format|
    @persona = Persona.find(params[:id])
      if @persona.update(persona_params)
        format.html { redirect_to @persona, notice: "La persona ha sido modificada con exito" }
        format.json { render :show, status: :ok, location: @persona }
      else
        @cargos = Cargo.all # Fetch all cargos again for the dropdown in case of errors
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personas/1 or /personas/1.json
  def destroy
    @persona.destroy

    respond_to do |format|
      format.html { redirect_to personas_path, status: :see_other, notice: "La persona ha sido eliminada exitosamente" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_persona
      @persona = Persona.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def persona_params
      params.require(:persona).permit(:id, :nombre, :edad, :cargo_id)
    end

  end

app/helpers/personas_helper.rb
module PersonasHelper
end

app/views/personas/_form.html.erb
<%= form_with(model: persona) do |form| %>
  <% if persona.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(persona.errors.count, "error") %> no se puede guardar:</h2>

      <ul>
        <% persona.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <% if @persona.errors.include?(:cargo_id) %>
  <div class="alert alert-danger" role="alert">
    ¡Debes seleccionar un cargo!
  </div>
  <% end %>

  <div class="form-group mb-3">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, class: 'form-control' %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :edad %>
    <%= form.number_field :edad, class: 'form-control' %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :cargo %>
    <%= form.collection_select :cargo_id, Cargo.all, :id, :descripcion, prompt: 'Seleccionar cargo' %>
  </div>

  <div class="d-flex justify-content-end">
    <%= form.submit 'Guardar', class: 'btn btn-primary me-2' %>
    <%= link_to 'Cancelar', personas_path, class: 'btn btn-secondary' %>
  </div>
<% end %>

app/views/personas/_persona.html.erb
<div class="card-body">
  <h5 class="card-title"><%= persona.nombre %></h5>
  <% if persona.cargo %>
    <p class="card-text">Cargo: <%= persona.cargo.descripcion %></p>
  <% end %>
  <%= link_to "Editar", edit_persona_path(persona) %>
  <%= link_to "Borrar", persona_path(persona), data: { turbo_method: :delete }, class: "text-danger" %>
</div>
<div class="card-footer d-flex justify-content-between">
  <span class="card-edad"><%= persona.edad %></span>
</div>

app/views/personas/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h1 class="text-center">Editar Persona</h1>

      <%= render 'form', persona: @persona %>
    </div>
  </div>
</div>

app/views/personas/index.html.erb
<div class="jumbotron bg-primary text-white">
  <h1 class="display-4">Personas</h1>
</div>

  <% if notice %>
    <p class="alert alert-info"><%= notice %></p>
  <% end %>

  <table class="table table-striped" style="margin: 0; padding: 0;">
    <thead>
      <tr>
        <th scope="col">Id</th>
        <th scope="col">Nombre</th>
        <th scope="col">Edad</th>
        <th scope="col">Cargo</th>
        <th colspan="3" class="text-center">Acciones</th>
      </tr>
    </thead>

    <tbody>
      <% @personas.each do |persona| %>
        <tr>
          <th scope="row"><%= persona.id %></th>
          <td><%= persona.nombre %></td>
          <td><%= persona.edad %></td>
          <td><%= persona.cargo ? persona.cargo.descripcion : "Sin cargo" %></td>
          <td class="col-md-2 text-center">
            <%= link_to 'Mostrar', persona, class: "btn btn-warning" %>
          </td>
          <td class="col-md-2 text-center">
            <%= link_to 'Editar', edit_persona_path(persona), class: "btn btn-primary" %>
          </td>
          <td class="col-md-2 text-center">
            <%= link_to 'Borrar', persona, method: :delete, data: { confirm: 'Estas seguro?' }, class: "btn btn-danger" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to "Nueva Persona", new_persona_path, class: "btn btn-success opacity-75" %>

  <div class="mt-3 p-3">
    <div class="row">
      <div class="col-12">
        </div>
    </div>
  </div>
</div>

app/views/personas/new.html.erb
<h1>Nueva Persona</h1>

<%= render 'form', persona: @persona %>

app/views/personas/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card">
        <div class="card-header">
          <h2>Detalles de la Persona</h2>
        </div>
        <div class="card-body">
          <ul class="list-group list-group-flush">
            <li class="list-group-item"><strong>ID:</strong> <span class="badge bg-primary"><%= @persona.id %></span></li>
            <li class="list-group-item"><strong>Nombre:</strong> <%= @persona.nombre %></li>
            <li class="list-group-item"><strong>Edad:</strong> <%= @persona.edad %></li>
            <li class="list-group-item"><strong>Cargo:</strong> 
              <% if @persona.cargo %>
                <%= @persona.cargo.descripcion %>
              <% else %>
                N/A
              <% end %>
            </li>
          </ul>
        </div>
      </div>

      <div class="card-footer text-muted">
        <%= link_to 'Editar', edit_persona_path(@persona), class: "btn btn-primary" %> |
        <%= link_to 'Volver', personas_path, class: "btn btn-secondary" %>
      </div>
    </div>
  </div>
</div>