config/routes.rb
Rails.application.routes.draw do
  resources :bombas
  resources :clientes do
    member do
      get 'bombas', to: 'clientes#bombas'
    end
  end  
  resources :empleados
  resources :paises
  resources :ciudades
  resources :ubicaciones
  resources :cargos
  # Defines the root path route ("/")
  root "personas#index"
  resources :personas
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bomba.rb
class Bomba < ApplicationRecord
    has_and_belongs_to_many :clientes
end

app/models/cargo.rb
class Cargo < ApplicationRecord
    has_many :personas
end

app/models/ciudade.rb
class Ciudade < ApplicationRecord
    belongs_to :paise, class_name: 'Paise', foreign_key: 'pais_id'
    validates :ciudad, :pais_id, presence: true
  end
  

app/models/cliente.rb
class Cliente < ApplicationRecord
    has_and_belongs_to_many :bombas
    validates :nombre, :razon_social, :ruc, presence: true
end

app/models/empleado.rb
class Empleado < ApplicationRecord
    belongs_to :persona, class_name: 'Persona', foreign_key: 'persona_id'
    belongs_to :cargo, class_name: 'Cargo', foreign_key: 'cargo_id'
    belongs_to :ubicacione, class_name: 'Ubicacione', foreign_key: 'ubicacion_id'
    belongs_to :ciudade, class_name: 'Ciudade', foreign_key: 'ciudad_id'
    belongs_to :paise, class_name: 'Paise', foreign_key: 'pais_id'
  
    validates :persona_id, :cargo_id, :ubicacion_id, :ciudad_id, :pais_id, presence: true
  end
  

app/models/paise.rb
class Paise < ApplicationRecord
    has_many :ciudades
end

app/models/persona.rb
class Persona < ApplicationRecord
    belongs_to :cargo
    validates :nombre, :edad, :cargo_id, presence: true
  end
  

app/models/ubicacione.rb
class Ubicacione < ApplicationRecord
    belongs_to :paise, class_name: 'Paise', foreign_key: 'pais_id'
    belongs_to :ciudade, class_name: 'Ciudade', foreign_key: 'ciudad_id'
    validates :direccion, :ciudad_id, :pais_id, presence: true
end

app/controllers/bombas_controller.rb
class BombasController < ApplicationController
  before_action :set_bomba, only: %i[ show edit update destroy ]

  # GET /bombas or /bombas.json
  def index
    @bombas = Bomba.all
  end

  # GET /bombas/1 or /bombas/1.json
  def show
  end

  # GET /bombas/new
  def new
    @bomba = Bomba.new
  end

  # GET /bombas/1/edit
  def edit
  end

  # POST /bombas or /bombas.json
  def create
    @bomba = Bomba.new(bomba_params)

    respond_to do |format|
      if @bomba.save
        format.html { redirect_to @bomba, notice: "La bomba ha sido creada con exito." }
        format.json { render :show, status: :created, location: @bomba }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bomba.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bombas/1 or /bombas/1.json
  def update
    respond_to do |format|
      if @bomba.update(bomba_params)
        format.html { redirect_to @bomba, notice: "La bomba se actualizo con exito." }
        format.json { render :show, status: :ok, location: @bomba }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bomba.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bombas/1 or /bombas/1.json
  def destroy
    @bomba.destroy

    respond_to do |format|
      format.html { redirect_to bombas_path, status: :see_other, notice: "bomba was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bomba
      @bomba = Bomba.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bomba_params
      params.require(:bomba).permit(:descripcion, :coordenadas)
    end
end

app/controllers/cargos_controller.rb
class CargosController < ApplicationController
  before_action :set_cargo, only: %i[ show edit update destroy ]

  # GET /cargos or /cargos.json
  def index
    @cargos = Cargo.all
  end

  # GET /cargos/1 or /cargos/1.json
  def show
  end

  # GET /cargos/new
  def new
    @cargo = Cargo.new
  end

  # GET /cargos/1/edit
  def edit
  end

  # POST /cargos or /cargos.json
  def create
    @cargo = Cargo.new(cargo_params)

    respond_to do |format|
      if @cargo.save
        format.html { redirect_to @cargo, notice: "Cargo was successfully created." }
        format.json { render :show, status: :created, location: @cargo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cargo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cargos/1 or /cargos/1.json
  def update
    respond_to do |format|
      if @cargo.update(cargo_params)
        format.html { redirect_to @cargo, notice: "Cargo was successfully updated." }
        format.json { render :show, status: :ok, location: @cargo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cargo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cargos/1 or /cargos/1.json
  def destroy
    @cargo.destroy

    respond_to do |format|
      format.html { redirect_to cargos_path, status: :see_other, notice: "Cargo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cargo
      @cargo = Cargo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cargo_params
      params.require(:cargo).permit(:descripcion, :sueldo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bombas_helper.rb
module BombasHelper
end

app/helpers/cargos_helper.rb
module CargosHelper
end

app/helpers/ciudades_helper.rb
module CiudadesHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/empleados_helper.rb
module EmpleadosHelper
end

app/helpers/paises_helper.rb
module PaisesHelper
end

app/helpers/personas_helper.rb
module PersonasHelper
end

app/helpers/ubicaciones_helper.rb
module UbicacionesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyApp</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_pack_tag 'application' %>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">CHRONOS</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to 'Empleados', empleados_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Personas', personas_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Cargos', cargos_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Ubicaciones', ubicaciones_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Países', paises_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Ciudades', ciudades_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Clientes', clientes_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Bombas', bombas_path, class: 'nav-link' %>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <div class="container mt-4">
    <%= yield %>
  </div>
</body>
</html>